In [336]:
import pandas as pd
import os
from pathlib import Path

# Define the futures directory
futures_dir = Path(r'Z:\Trade_Control\Options')

# Get all CSV files
csv_files = sorted([f for f in futures_dir.glob('*.csv')])
print(f"Found {len(csv_files)} CSV files in {futures_dir}")
print("\nFiles:")
for i, file in enumerate(csv_files[:23]):  # Show first 10
    print(f"{i}: {file.name}")

Found 23 CSV files in Z:\Trade_Control\Options

Files:
0: Options_20250717_1400.csv
1: Options_20250717_1500.csv
2: Options_20250717_1600.csv
3: Options_20250718_1104.csv
4: Options_20250718_1404.csv
5: Options_20250718_1500.csv
6: Options_20250718_1601.csv
7: Options_20250718_1851.csv
8: Options_20250721_1401.csv
9: Options_20250721_1601.csv
10: Options_20250722_1402.csv
11: Options_20250722_1500.csv
12: Options_20250722_1600.csv
13: Options_20250723_1402.csv
14: Options_20250723_1501.csv
15: Options_20250724_1401.csv
16: Options_20250725_1401.csv
17: Options_20250728_1501.csv
18: Options_20250729_1401.csv
19: Options_20250730_1401.csv
20: Options_20250731_1402.csv
21: Options_20250731_1539.csv
22: Options_20250801_1401.csv

In [337]:
pricing_dfs = []

In [338]:
# File 2
file_idx = 1
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250717_1500.csv
Shape: (280, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                      symbol price_type                      price  \
0    VBYN25C2 112.250 Comdty      close  #N/A Field Not Applicable
1    VBYN25C2 112.000 Comdty      close  #N/A Field Not Applicable
2    VBYN25C2 111.750 Comdty      close  #N/A Field Not Applicable
3    VBYN25C2 111.500 Comdty      close  #N/A Field Not Applicable
4    VBYN25C2 111.250 Comdty      close  #N/A Field Not Applicable
..                       ...        ...                        ...
275     TYQ5P 111.250 Comdty      close                   0.796875
276     TYQ5P 111.500 Comdty      close                    1.03125
277     TYQ5P 111.750 Comdty      close                   1.265625
278     TYQ5P 112.000 Comdty      close                        1.5
279     TYQ5P 112.250 Comdty      close                       1.75

            timestamp
0    2025-07-17 15:00
1    2025-07-17 15:00
2    2025-07-17 15:00
3    2025-07-17 15:00
4    2025-07-17 15:00
..                ...
275  2025-07-17 15:00
276  2025-07-17 15:00
277  2025-07-17 15:00
278  2025-07-17 15:00
279  2025-07-17 15:00

[280 rows x 4 columns]

In [339]:
# File 7
file_idx = 6
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250718_1601.csv
Shape: (280, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                   symbol price_type     price         timestamp
0    3MN5C 112.250 Comdty      close  0.000000  2025-07-18 16:01
1    3MN5C 112.000 Comdty      close  0.000000  2025-07-18 16:01
2    3MN5C 111.750 Comdty      close  0.000000  2025-07-18 16:01
3    3MN5C 111.500 Comdty      close  0.000000  2025-07-18 16:01
4    3MN5C 111.250 Comdty      close  0.000000  2025-07-18 16:01
..                    ...        ...       ...               ...
275  2MQ5P 111.250 Comdty      close  0.828125  2025-07-18 16:01
276  2MQ5P 111.500 Comdty      close  1.000000  2025-07-18 16:01
277  2MQ5P 111.750 Comdty      close  1.171875  2025-07-18 16:01
278  2MQ5P 112.000 Comdty      close  1.375000  2025-07-18 16:01
279  2MQ5P 112.250 Comdty      close  1.593750  2025-07-18 16:01

[280 rows x 4 columns]

In [340]:
# File 10
file_idx = 9
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250721_1601.csv
Shape: (280, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                   symbol price_type     price         timestamp
0    3MN5C 112.250 Comdty      close  0.000000  2025-07-21 16:01
1    3MN5C 112.000 Comdty      close  0.000000  2025-07-21 16:01
2    3MN5C 111.750 Comdty      close  0.000000  2025-07-21 16:01
3    3MN5C 111.500 Comdty      close  0.000000  2025-07-21 16:01
4    3MN5C 111.250 Comdty      close  0.000000  2025-07-21 16:01
..                    ...        ...       ...               ...
275  2MQ5P 111.250 Comdty      close  0.593750  2025-07-21 16:01
276  2MQ5P 111.500 Comdty      close  0.734375  2025-07-21 16:01
277  2MQ5P 111.750 Comdty      close  0.890625  2025-07-21 16:01
278  2MQ5P 112.000 Comdty      close  1.062500  2025-07-21 16:01
279  2MQ5P 112.250 Comdty      close  1.265625  2025-07-21 16:01

[280 rows x 4 columns]

In [341]:
# File 12
file_idx = 11
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250722_1500.csv
Shape: (246, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                      symbol price_type     price         timestamp
0    TJPN25C4 112.750 Comdty      close  0.007000  2025-07-22 15:00
1    TJPN25C4 112.500 Comdty      close  0.007000  2025-07-22 15:00
2    TJPN25C4 112.250 Comdty      close  0.007000  2025-07-22 15:00
3    TJPN25C4 112.000 Comdty      close  0.007000  2025-07-22 15:00
4    TJPN25C4 111.750 Comdty      close  0.007000  2025-07-22 15:00
..                       ...        ...       ...               ...
241     1MQ5C 110.500 Comdty      close  1.046875  2025-07-22 15:00
242     1MQ5C 110.750 Comdty      close  0.843750  2025-07-22 15:00
243     1MQ5C 111.000 Comdty      close  0.687500  2025-07-22 15:00
244     1MQ5C 111.250 Comdty      close  0.531250  2025-07-22 15:00
245     1MQ5P 111.250 Comdty      close  0.375000  2025-07-22 15:00

[246 rows x 4 columns]

In [342]:
# File 15
file_idx = 14
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250723_1501.csv
Shape: (246, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                      symbol price_type                      price  \
0    TJPN25C4 112.750 Comdty      close  #N/A Field Not Applicable
1    TJPN25C4 112.500 Comdty      close  #N/A Field Not Applicable
2    TJPN25C4 112.250 Comdty      close  #N/A Field Not Applicable
3    TJPN25C4 112.000 Comdty      close  #N/A Field Not Applicable
4    TJPN25C4 111.750 Comdty      close  #N/A Field Not Applicable
..                       ...        ...                        ...
241     1MQ5C 110.500 Comdty      close                    0.71875
242     1MQ5C 110.750 Comdty      close                     0.5625
243     1MQ5C 111.000 Comdty      close                   0.421875
244     1MQ5C 111.250 Comdty      close                     0.3125
245     1MQ5P 111.250 Comdty      close                   0.546875

            timestamp
0    2025-07-23 15:01
1    2025-07-23 15:01
2    2025-07-23 15:01
3    2025-07-23 15:01
4    2025-07-23 15:01
..                ...
241  2025-07-23 15:01
242  2025-07-23 15:01
243  2025-07-23 15:01
244  2025-07-23 15:01
245  2025-07-23 15:01

[246 rows x 4 columns]

In [343]:
# File 16
file_idx = 15
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250724_1401.csv
Shape: (246, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                      symbol price_type                      price  \
0    TJPN25C4 112.750 Comdty      close  #N/A Field Not Applicable
1    TJPN25C4 112.500 Comdty      close  #N/A Field Not Applicable
2    TJPN25C4 112.250 Comdty      close  #N/A Field Not Applicable
3    TJPN25C4 112.000 Comdty      close  #N/A Field Not Applicable
4    TJPN25C4 111.750 Comdty      close  #N/A Field Not Applicable
..                       ...        ...                        ...
241     1MQ5C 110.500 Comdty      close                    0.71875
242     1MQ5C 110.750 Comdty      close                     0.5625
243     1MQ5C 111.000 Comdty      close                   0.421875
244     1MQ5C 111.250 Comdty      close                     0.3125
245     1MQ5P 111.250 Comdty      close                   0.546875

            timestamp
0    2025-07-24 14:01
1    2025-07-24 14:01
2    2025-07-24 14:01
3    2025-07-24 14:01
4    2025-07-24 14:01
..                ...
241  2025-07-24 14:01
242  2025-07-24 14:01
243  2025-07-24 14:01
244  2025-07-24 14:01
245  2025-07-24 14:01

[246 rows x 4 columns]

In [344]:
# File 17
file_idx = 16
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250725_1401.csv
Shape: (246, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                      symbol price_type                      price  \
0    TJPN25C4 112.750 Comdty      close  #N/A Field Not Applicable
1    TJPN25C4 112.500 Comdty      close  #N/A Field Not Applicable
2    TJPN25C4 112.250 Comdty      close  #N/A Field Not Applicable
3    TJPN25C4 112.000 Comdty      close  #N/A Field Not Applicable
4    TJPN25C4 111.750 Comdty      close  #N/A Field Not Applicable
..                       ...        ...                        ...
241     1MQ5C 110.500 Comdty      close                   0.578125
242     1MQ5C 110.750 Comdty      close                   0.421875
243     1MQ5C 111.000 Comdty      close                     0.3125
244     1MQ5C 111.250 Comdty      close                    0.21875
245     1MQ5P 111.250 Comdty      close                   0.640625

            timestamp
0    2025-07-25 14:01
1    2025-07-25 14:01
2    2025-07-25 14:01
3    2025-07-25 14:01
4    2025-07-25 14:01
..                ...
241  2025-07-25 14:01
242  2025-07-25 14:01
243  2025-07-25 14:01
244  2025-07-25 14:01
245  2025-07-25 14:01

[246 rows x 4 columns]

In [345]:
# File 18
file_idx = 17
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250728_1501.csv
Shape: (1008, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                      symbol price_type     price         timestamp
0     VBYN25P4 113.75 Comdty      close  2.984375  2025-07-28 15:01
1      VBYN25P4 113.5 Comdty      close  2.734375  2025-07-28 15:01
2     VBYN25P4 113.25 Comdty      close  2.484375  2025-07-28 15:01
3        VBYN25P4 113 Comdty      close  2.234375  2025-07-28 15:01
4     VBYN25P4 112.75 Comdty      close  1.984375  2025-07-28 15:01
...                      ...        ...       ...               ...
1003                       0      close         0  2025-07-28 15:01
1004                       0      close         0  2025-07-28 15:01
1005                       0      close         0  2025-07-28 15:01
1006                       0      close         0  2025-07-28 15:01
1007                       0      close         0  2025-07-28 15:01

[1008 rows x 4 columns]

In [346]:
# File 19
file_idx = 18
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250729_1401.csv
Shape: (384, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                     symbol price_type  \
0    TJPN25P5 114.25 Comdty      close
1       TJPN25P5 114 Comdty      close
2    TJPN25P5 113.75 Comdty      close
3     TJPN25P5 113.5 Comdty      close
4    TJPN25P5 113.25 Comdty      close
..                      ...        ...
379                     0.0      close
380                     0.0      close
381                     0.0      close
382                     0.0      close
383                     0.0      close

                                                 price         timestamp
0                                             2.890625  2025-07-29 14:01
1                                             2.640625  2025-07-29 14:01
2                                             2.390625  2025-07-29 14:01
3                                             2.140625  2025-07-29 14:01
4                                             1.890625  2025-07-29 14:01
..                                                 ...               ...
379  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-29 14:01
380  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-29 14:01
381  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-29 14:01
382  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-29 14:01
383  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-29 14:01

[384 rows x 4 columns]

In [347]:
# File 20
file_idx = 19
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250730_1401.csv
Shape: (384, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                          symbol price_type  \
0       TYWN25P5 114 COMB Comdty      close
1    TYWN25P5 113.75 COMB Comdty      close
2     TYWN25P5 113.5 COMB Comdty      close
3    TYWN25P5 113.25 COMB Comdty      close
4       TYWN25P5 113 COMB Comdty      close
..                           ...        ...
379                          0.0      close
380                          0.0      close
381                          0.0      close
382                          0.0      close
383                          0.0      close

                                                 price         timestamp
0                                                  3.0  2025-07-30 14:01
1                                                 2.75  2025-07-30 14:01
2                                                  2.5  2025-07-30 14:01
3                                                 2.25  2025-07-30 14:01
4                                                  2.0  2025-07-30 14:01
..                                                 ...               ...
379  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-30 14:01
380  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-30 14:01
381  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-30 14:01
382  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-30 14:01
383  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-30 14:01

[384 rows x 4 columns]

In [348]:
# File 22
file_idx = 21
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250731_1539.csv

Shape: (384, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                          symbol price_type  \
0       1MQ5P    114 COMB Comdty      close
1    1MQ5P    113.75 COMB Comdty      close
2     1MQ5P    113.5 COMB Comdty      close
3    1MQ5P    113.25 COMB Comdty      close
4       1MQ5P    113 COMB Comdty      close
..                           ...        ...
379                          0.0      close
380                          0.0      close
381                          0.0      close
382                          0.0      close
383                          0.0      close

                                                 price         timestamp
0                                               2.9375  2025-07-31 15:39
1                                               2.6875  2025-07-31 15:39
2                                               2.4375  2025-07-31 15:39
3                                               2.1875  2025-07-31 15:39
4                                               1.9375  2025-07-31 15:39
..                                                 ...               ...
379  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-31 15:39
380  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-31 15:39
381  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-31 15:39
382  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-31 15:39
383  #N/A Mandatory parameter [SECURITY] cannot be ...  2025-07-31 15:39

[384 rows x 4 columns]

In [349]:
# File 22
file_idx = 22
if file_idx < len(csv_files):
    file = csv_files[file_idx]
    print(f"File: {file.name}")
    df = pd.read_csv(file)
    # Filter columns: keep SYMBOL, PX_SETTLE, and 'Settle Price = Today' if present
    cols_to_keep = ['SYMBOL', 'PX_SETTLE']
    if 'Settle Price = Today' in df.columns:
        cols_to_keep.append('Settle Price = Today')
    df = df[cols_to_keep]
    
    # Extract and format timestamp from filename
    date_time = file.name.replace('Options_', '').replace('.csv', '')
    date_part = date_time[:8]
    time_part = date_time[9:]
    timestamp = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]} {time_part[:2]}:{time_part[2:]}"
    
    # Rename columns and add price_type
    df = df.rename(columns={'SYMBOL': 'symbol', 'PX_SETTLE': 'price'})
    df['price_type'] = 'close'
    df['timestamp'] = timestamp
    
    # Reorder columns
    df = df[['symbol', 'price_type', 'price', 'timestamp']]
    
    print(f"Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print("\nDataFrame:")
    print(df)
    pricing_dfs.append(df)

File: Options_20250801_1401.csv
Shape: (385, 4)
Columns: ['symbol', 'price_type', 'price', 'timestamp']

DataFrame:
                          symbol price_type     price         timestamp
0       1MQ5P    115 COMB Comdty      close  2.796875  2025-08-01 14:01
1    1MQ5P    114.75 COMB Comdty      close  2.546875  2025-08-01 14:01
2     1MQ5P    114.5 COMB Comdty      close  2.296875  2025-08-01 14:01
3    1MQ5P    114.25 COMB Comdty      close  2.046875  2025-08-01 14:01
4       1MQ5P    114 COMB Comdty      close  1.796875  2025-08-01 14:01
..                           ...        ...       ...               ...
380   TYWQ25C2 109.5 COMB Comdty      close  1.609375  2025-08-01 14:01
381   TYWQ25P2 109.5 COMB Comdty      close  0.046875  2025-08-01 14:01
382  TYWQ25C2 109.25 COMB Comdty      close  1.843750  2025-08-01 14:01
383  TYWQ25P2 109.25 COMB Comdty      close  0.031250  2025-08-01 14:01
384      TJWQ25C1 112.500 Comdty      close  0.171875  2025-08-01 14:01

[385 rows x 4 columns]

In [350]:
# Combine all dataframes into one
combined_df = pd.concat(pricing_dfs, ignore_index=True)

# Display the combined dataframe
print(f"Combined DataFrame Shape: {combined_df.shape}")
print(f"Total rows: {len(combined_df)}")
print("\nCombined DataFrame:")
display(combined_df)

Combined DataFrame Shape: (4369, 4)
Total rows: 4369

Combined DataFrame:

,symbol,price_type,price,timestamp
0,VBYN25C2 112.250 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
1,VBYN25C2 112.000 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
2,VBYN25C2 111.750 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
3,VBYN25C2 111.500 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
4,VBYN25C2 111.250 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
...,...,...,...,...
4364,TYWQ25C2 109.5 COMB Comdty,close,1.609375,2025-08-01 14:01
4365,TYWQ25P2 109.5 COMB Comdty,close,0.046875,2025-08-01 14:01
4366,TYWQ25C2 109.25 COMB Comdty,close,1.84375,2025-08-01 14:01
4367,TYWQ25P2 109.25 COMB Comdty,close,0.03125,2025-08-01 14:01
4368,TJWQ25C1 112.500 Comdty,close,0.171875,2025-08-01 14:01

In [351]:
# Remove 'COMB' from symbol column
combined_df['symbol'] = combined_df['symbol'].str.replace('COMB', '', regex=False)

# Display to verify the change
print(f"Combined DataFrame Shape: {combined_df.shape}")
print(f"Total rows: {len(combined_df)}")
print("\nFirst few rows after removing COMB:")
display(combined_df)

Combined DataFrame Shape: (4369, 4)
Total rows: 4369

First few rows after removing COMB:

,symbol,price_type,price,timestamp
0,VBYN25C2 112.250 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
1,VBYN25C2 112.000 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
2,VBYN25C2 111.750 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
3,VBYN25C2 111.500 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
4,VBYN25C2 111.250 Comdty,close,#N/A Field Not Applicable,2025-07-17 15:00
...,...,...,...,...
4364,TYWQ25C2 109.5 Comdty,close,1.609375,2025-08-01 14:01
4365,TYWQ25P2 109.5 Comdty,close,0.046875,2025-08-01 14:01
4366,TYWQ25C2 109.25 Comdty,close,1.84375,2025-08-01 14:01
4367,TYWQ25P2 109.25 Comdty,close,0.03125,2025-08-01 14:01
4368,TJWQ25C1 112.500 Comdty,close,0.171875,2025-08-01 14:01

In [ ]:
# First, let's identify all non-numeric values in the price column
# Convert price to numeric, marking errors as NaN
combined_df['price_numeric'] = pd.to_numeric(combined_df['price'], errors='coerce')

# Find rows where conversion failed (non-numeric values)
non_numeric_mask = combined_df['price_numeric'].isna()
non_numeric_prices = combined_df[non_numeric_mask]

print(f"Found {len(non_numeric_prices)} rows with non-numeric prices out of {len(combined_df)} total rows")
print(f"That's {len(non_numeric_prices)/len(combined_df)*100:.2f}% of the data\n")

# Show unique non-numeric values and their counts
print("Unique non-numeric price values:")
print(non_numeric_prices['price'].value_counts())
print("\n")

# Show a sample of affected rows
print("Sample of affected rows (first 10):")
non_numeric_prices[['symbol', 'price', 'timestamp']].head(10)

Found 263 rows with non-numeric prices out of 4369 total rows
That's 6.02% of the data

Unique non-numeric price values:
price
#N/A Mandatory parameter [SECURITY] cannot be empty    179
#N/A Field Not Applicable                               84
Name: count, dtype: int64


Sample of affected rows (first 10):

                     symbol                      price         timestamp
0   VBYN25C2 112.250 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
1   VBYN25C2 112.000 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
2   VBYN25C2 111.750 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
3   VBYN25C2 111.500 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
4   VBYN25C2 111.250 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
5   VBYN25C2 111.000 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
7   VBYN25P2 110.750 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
8   VBYN25P2 110.500 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
9   VBYN25P2 110.250 Comdty  #N/A Field Not Applicable  2025-07-17 15:00
10  VBYN25P2 110.000 Comdty  #N/A Field Not Applicable  2025-07-17 15:00

In [ ]:
# Execute the cleaning - remove all rows with non-numeric prices
cleaned_df = combined_df[~non_numeric_mask].copy()
cleaned_df = cleaned_df.drop(columns=['price_numeric'])
cleaned_df['price'] = pd.to_numeric(cleaned_df['price'])  # Ensure price is numeric type

print("=== CLEANING COMPLETE ===\n")
print(f"Original rows: {len(combined_df):,}")
print(f"Cleaned rows: {len(cleaned_df):,}")
print(f"Rows removed: {len(combined_df) - len(cleaned_df):,}")
print(f"Percentage removed: {(len(combined_df) - len(cleaned_df))/len(combined_df)*100:.2f}%")

# Replace the original with cleaned version
combined_df = cleaned_df

print("\n=== VERIFICATION ===")
print(f"Data type of price column: {combined_df['price'].dtype}")
print(f"Any non-numeric values remaining: {pd.to_numeric(combined_df['price'], errors='coerce').isna().sum()}")

# Show summary statistics of the cleaned price column
print("\nPrice column statistics:")
print(combined_df['price'].describe())

# Display first few rows to verify
print("\nFirst 10 rows of cleaned data:")
combined_df.head(10)

=== CLEANING COMPLETE ===

Original rows: 4,369
Cleaned rows: 4,106
Rows removed: 263
Percentage removed: 6.02%

=== VERIFICATION ===
Data type of price column: float64
Any non-numeric values remaining: 0

Price column statistics:
count    4106.000000
mean        0.567970
std         0.797734
min         0.000000
25%         0.001000
50%         0.140625
75%         0.921875
max         3.953125
Name: price, dtype: float64

First 10 rows of cleaned data:

                     symbol price_type     price         timestamp
6   VBYN25C2 110.750 Comdty      close  0.015625  2025-07-17 15:00
14  VBYN25C2 109.250 Comdty      close  1.515625  2025-07-17 15:00
15  VBYN25C2 109.500 Comdty      close  1.265625  2025-07-17 15:00
16  VBYN25C2 109.750 Comdty      close  1.015625  2025-07-17 15:00
17  VBYN25C2 110.000 Comdty      close  0.765625  2025-07-17 15:00
18  VBYN25C2 110.250 Comdty      close  0.515625  2025-07-17 15:00
19  VBYN25C2 110.500 Comdty      close  0.265625  2025-07-17 15:00
20  VBYN25C2 110.750 Comdty      close  0.015625  2025-07-17 15:00
22  VBYN25P2 111.000 Comdty      close  0.234375  2025-07-17 15:00
23  VBYN25P2 111.250 Comdty      close  0.484375  2025-07-17 15:00

In [ ]:
# Investigate the trades.db structure
import sqlite3

# Connect to the database
conn = sqlite3.connect('../trades.db')
cursor = conn.cursor()

# Get all tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("=== TABLES IN trades.db ===")
for table in tables:
    print(f"  - {table[0]}")

# Check if pricing table exists
if ('pricing',) in tables:
    print("\n✓ 'pricing' table found!")
else:
    print("\n✗ 'pricing' table NOT found!")
    
conn.close()

=== TABLES IN trades.db ===
  - sqlite_sequence
  - price_file_tracker
  - processed_files
  - trades_fifo
  - trades_lifo
  - realized_fifo
  - realized_lifo
  - pricing
  - daily_positions
  - positions

✓ 'pricing' table found!

In [ ]:
# Investigate the pricing table structure
conn = sqlite3.connect('../trades.db')
cursor = conn.cursor()

# Get table schema
print("=== PRICING TABLE SCHEMA ===")
cursor.execute("PRAGMA table_info(pricing);")
columns = cursor.fetchall()

print("\nColumns in 'pricing' table:")
print(f"{'Column Name':<20} {'Type':<15} {'Nullable':<10} {'Default':<10} {'Primary Key'}")
print("-" * 70)
for col in columns:
    col_name = col[1]
    col_type = col[2]
    not_null = 'NOT NULL' if col[3] else 'NULL'
    default = col[4] if col[4] else 'None'
    is_pk = 'PK' if col[5] else ''
    print(f"{col_name:<20} {col_type:<15} {not_null:<10} {default:<10} {is_pk}")

# Get some sample data
print("\n=== SAMPLE DATA FROM PRICING TABLE ===")
cursor.execute("SELECT * FROM pricing LIMIT 5;")
sample_data = cursor.fetchall()

if sample_data:
    # Get column names
    column_names = [description[0] for description in cursor.description]
    print(f"\nColumns: {column_names}")
    print("\nSample rows:")
    for i, row in enumerate(sample_data):
        print(f"Row {i+1}: {row}")
else:
    print("No data in pricing table yet")

# Get row count
cursor.execute("SELECT COUNT(*) FROM pricing;")
count = cursor.fetchone()[0]
print(f"\nTotal rows in pricing table: {count}")

conn.close()

=== PRICING TABLE SCHEMA ===

Columns in 'pricing' table:
Column Name          Type            Nullable   Default    Primary Key
----------------------------------------------------------------------
symbol               TEXT            NULL       None       PK
price_type           TEXT            NULL       None       PK
price                REAL            NULL       None
timestamp            TEXT            NULL       None

=== SAMPLE DATA FROM PRICING TABLE ===

Columns: ['symbol', 'price_type', 'price', 'timestamp']

Sample rows:
Row 1: ('1MQ5C 111.75 Comdty', 'close', 0.03125, '2025-07-31 16:00:00')
Row 2: ('TUU5 Comdty', 'close', 103.9609375, '2025-08-01 14:00:00')
Row 3: ('TUU5 Comdty', 'sodTom', 103.9609375, '2025-08-01 14:00:00')
Row 4: ('FVU5 Comdty', 'close', 109.0234375, '2025-08-01 14:00:00')
Row 5: ('FVU5 Comdty', 'sodTom', 109.0234375, '2025-08-01 14:00:00')

Total rows in pricing table: 1126

In [ ]:
# === CLEAN DATA PREPARATION FOR DATABASE INSERTION ===
print("=== PREPARING DATA FOR DATABASE INSERTION ===\n")

# Start with our cleaned dataframe (non-numeric prices already removed)
insert_df = combined_df.copy()
print(f"Starting with {len(insert_df)} rows")

# 0. First, normalize symbols by replacing multiple spaces with single space
print("\n0. Normalizing symbol spacing...")
# Convert symbol to string and strip leading/trailing whitespace
insert_df['symbol'] = insert_df['symbol'].astype(str).str.strip()
# Replace multiple spaces with single space
insert_df['symbol'] = insert_df['symbol'].str.replace(r'\s+', ' ', regex=True)
print("   ✓ Replaced multiple spaces with single spaces in symbols")

# 1. Remove invalid symbols (0, 0.0, empty, etc.)
print("\n1. Checking for and removing invalid symbols (0, 0.0, empty, etc.)...")
# Find problematic symbols
invalid_symbols = insert_df[
    (insert_df['symbol'] == '0') | 
    (insert_df['symbol'] == '0.0') |
    (insert_df['symbol'] == '') |
    (insert_df['symbol'].isna()) |
    (insert_df['symbol'].str.match(r'^[\d\.]+$', na=False))  # Any pure number
]

if len(invalid_symbols) > 0:
    print(f"   Found {len(invalid_symbols)} rows with invalid symbols:")
    print(f"   Symbol values: {invalid_symbols['symbol'].value_counts().to_dict()}")
    print(f"   Sample of invalid rows:")
    print(invalid_symbols[['symbol', 'price', 'timestamp']].head())
    
    # Remove these rows
    insert_df = insert_df[~insert_df.index.isin(invalid_symbols.index)]
    print(f"   Removed {len(invalid_symbols)} rows with invalid symbols")
    print(f"   Rows remaining: {len(insert_df)}")

# 2. Remove exact duplicates (where ALL columns are the same)
print("\n2. Removing exact duplicates...")
before_dedup = len(insert_df)
insert_df = insert_df.drop_duplicates()
after_dedup = len(insert_df)
print(f"   Removed {before_dedup - after_dedup} exact duplicate rows")

# 3. Check for symbol-timestamp duplicates with different prices
print("\n3. Checking for symbol-timestamp duplicates with different prices...")
dup_check = insert_df.groupby(['symbol', 'timestamp']).agg({
    'price': ['count', 'nunique', lambda x: list(x.unique())]
}).reset_index()
dup_check.columns = ['symbol', 'timestamp', 'count', 'unique_prices', 'price_list']
conflicts = dup_check[dup_check['unique_prices'] > 1]

if len(conflicts) > 0:
    print(f"   WARNING: Found {len(conflicts)} symbol-timestamp pairs with DIFFERENT prices:")
    for _, row in conflicts.head(10).iterrows():
        print(f"   Symbol: {row['symbol']}, Time: {row['timestamp']}, Prices: {row['price_list']}")
else:
    print("   ✓ No price conflicts found")

# 4. Remove remaining duplicates, keeping last
print("\n4. Removing remaining duplicates (keeping last occurrence)...")
before_final = len(insert_df)
insert_df = insert_df.drop_duplicates(subset=['symbol', 'timestamp'], keep='last')
after_final = len(insert_df)
print(f"   Removed {before_final - after_final} duplicate rows")

# 5. Format timestamp to include seconds
print("\n5. Formatting timestamps...")
insert_df['timestamp'] = insert_df['timestamp'] + ':00'
print(f"   Sample timestamp: {insert_df['timestamp'].iloc[0]}")

# 6. Convert price to string
print("\n6. Converting price to string...")
insert_df['price'] = insert_df['price'].astype(str)

# 7. Final verification
print("\n=== FINAL DATA READY FOR INSERTION ===")
print(f"Total rows: {len(insert_df)}")
print(f"Data types: {dict(insert_df.dtypes)}")
print(f"\nSample data with normalized symbols:")
print(insert_df.head())

# Double-check for any remaining weird symbols
weird_symbols = insert_df[insert_df['symbol'].str.match(r'^[\d\.]+$', na=False)]
if len(weird_symbols) > 0:
    print(f"\nERROR: Still found {len(weird_symbols)} rows with numeric-only symbols!")
    print("This should not happen - please investigate further")
else:
    print(f"\n✓ All symbols are valid (no numeric-only symbols found)")

=== PREPARING DATA FOR DATABASE INSERTION ===

Starting with 4106 rows

0. Normalizing symbol spacing...
   ✓ Replaced multiple spaces with single spaces in symbols

1. Checking for and removing invalid symbols (0, 0.0, empty, etc.)...
   Found 575 rows with invalid symbols:
   Symbol values: {'0': 575}
   Sample of invalid rows:
     symbol  price         timestamp
2256      0    0.0  2025-07-28 15:01
2257      0    0.0  2025-07-28 15:01
2258      0    0.0  2025-07-28 15:01
2259      0    0.0  2025-07-28 15:01
2260      0    0.0  2025-07-28 15:01
   Removed 575 rows with invalid symbols
   Rows remaining: 3531

2. Removing exact duplicates...
   Removed 184 exact duplicate rows

3. Checking for symbol-timestamp duplicates with different prices...
   ✓ No price conflicts found

4. Removing remaining duplicates (keeping last occurrence)...
   Removed 0 duplicate rows

5. Formatting timestamps...
   Sample timestamp: 2025-07-17 15:00:00

6. Converting price to string...

=== FINAL DATA READY FOR INSERTION ===
Total rows: 3347
Data types: {'symbol': dtype('O'), 'price_type': dtype('O'), 'price': dtype('O'), 'timestamp': dtype('O')}

Sample data with normalized symbols:
                     symbol price_type     price            timestamp
6   VBYN25C2 110.750 Comdty      close  0.015625  2025-07-17 15:00:00
14  VBYN25C2 109.250 Comdty      close  1.515625  2025-07-17 15:00:00
15  VBYN25C2 109.500 Comdty      close  1.265625  2025-07-17 15:00:00
16  VBYN25C2 109.750 Comdty      close  1.015625  2025-07-17 15:00:00
17  VBYN25C2 110.000 Comdty      close  0.765625  2025-07-17 15:00:00

✓ All symbols are valid (no numeric-only symbols found)

In [ ]:
# === DATABASE INSERTION ===
print("=== INSERTING DATA INTO DATABASE ===\n")

# Connect to database
conn = sqlite3.connect('../trades.db')
cursor = conn.cursor()

try:
    # Get initial count
    cursor.execute("SELECT COUNT(*) FROM pricing")
    initial_count = cursor.fetchone()[0]
    print(f"Initial row count in pricing table: {initial_count}")
    
    # Convert dataframe to list of tuples for insertion
    records = insert_df[['symbol', 'price_type', 'price', 'timestamp']].values.tolist()
    
    # Insert in batches for better performance
    batch_size = 500
    total_inserted = 0
    
    for i in range(0, len(records), batch_size):
        batch = records[i:i+batch_size]
        
        # Use INSERT OR REPLACE to handle conflicts with existing data
        cursor.executemany("""
            INSERT OR REPLACE INTO pricing (symbol, price_type, price, timestamp)
            VALUES (?, ?, ?, ?)
        """, batch)
        
        total_inserted += len(batch)
        print(f"   Inserted batch {i//batch_size + 1}: {len(batch)} rows (Total: {total_inserted}/{len(records)})")
    
    # Commit the transaction
    conn.commit()
    print(f"\n✓ Successfully inserted/updated {total_inserted} records")
    
    # Get final count
    cursor.execute("SELECT COUNT(*) FROM pricing")
    final_count = cursor.fetchone()[0]
    print(f"\nFinal row count in pricing table: {final_count}")
    print(f"Net new rows added: {final_count - initial_count}")
    
    # Show sample of inserted data
    print("\nSample of data in database after insertion:")
    cursor.execute("SELECT * FROM pricing WHERE price_type = 'close' ORDER BY timestamp DESC LIMIT 5")
    for row in cursor.fetchall():
        print(f"   {row}")
        
except Exception as e:
    print(f"❌ Error during insertion: {e}")
    conn.rollback()
    
finally:
    conn.close()
    print("\n✓ Database connection closed")

=== INSERTING DATA INTO DATABASE ===

Initial row count in pricing table: 1126
   Inserted batch 1: 500 rows (Total: 500/3347)
   Inserted batch 2: 500 rows (Total: 1000/3347)
   Inserted batch 3: 500 rows (Total: 1500/3347)
   Inserted batch 4: 500 rows (Total: 2000/3347)
   Inserted batch 5: 500 rows (Total: 2500/3347)
   Inserted batch 6: 500 rows (Total: 3000/3347)
   Inserted batch 7: 347 rows (Total: 3347/3347)

✓ Successfully inserted/updated 3347 records

Final row count in pricing table: 1399
Net new rows added: 273

Sample of data in database after insertion:
   ('1MQ5P    115  Comdty', 'close', 2.796875, '2025-08-01 14:01:00')
   ('1MQ5P    114.75  Comdty', 'close', 2.546875, '2025-08-01 14:01:00')
   ('1MQ5P    114.5  Comdty', 'close', 2.296875, '2025-08-01 14:01:00')
   ('1MQ5P    114.25  Comdty', 'close', 2.046875, '2025-08-01 14:01:00')
   ('1MQ5P    114  Comdty', 'close', 1.796875, '2025-08-01 14:01:00')

✓ Database connection closed

In [ ]:
# === STEP 1: ANALYZE SYMBOL SPACING ISSUE ===
print("=== ANALYZING SYMBOL SPACING ===\n")

# Check current state of symbols in our dataframe
print("Sample symbols before normalization:")
sample_symbols = combined_df['symbol'].head(20).tolist()
for i, sym in enumerate(sample_symbols[:10]):
    # Show the symbol with quotes to see spaces clearly
    print(f"  {i+1}: '{sym}' (length: {len(sym)})")

# Check for multiple spaces
multi_space_symbols = combined_df[combined_df['symbol'].str.contains('  ', regex=False)]
print(f"\nRows with multiple spaces in symbol: {len(multi_space_symbols)}")
if len(multi_space_symbols) > 0:
    print("\nExamples of symbols with multiple spaces:")
    for sym in multi_space_symbols['symbol'].head(5):
        print(f"  '{sym}'")

=== ANALYZING SYMBOL SPACING ===

Sample symbols before normalization:
  1: 'VBYN25C2 110.750 Comdty' (length: 23)
  2: 'VBYN25C2 109.250 Comdty' (length: 23)
  3: 'VBYN25C2 109.500 Comdty' (length: 23)
  4: 'VBYN25C2 109.750 Comdty' (length: 23)
  5: 'VBYN25C2 110.000 Comdty' (length: 23)
  6: 'VBYN25C2 110.250 Comdty' (length: 23)
  7: 'VBYN25C2 110.500 Comdty' (length: 23)
  8: 'VBYN25C2 110.750 Comdty' (length: 23)
  9: 'VBYN25P2 111.000 Comdty' (length: 23)
  10: 'VBYN25P2 111.250 Comdty' (length: 23)

Rows with multiple spaces in symbol: 920

Examples of symbols with multiple spaces:
  'TYWN25P5 113.75  Comdty'
  'TYWN25P5 113.5  Comdty'
  'TYWN25P5 113.25  Comdty'
  'TYWN25P5 113  Comdty'
  'TYWN25P5 112.75  Comdty'

In [ ]:
# === STEP 2: DROP ALL CLOSE PRICES FROM DATABASE ===
print("=== REMOVING EXISTING CLOSE PRICES FROM DATABASE ===\n")

conn = sqlite3.connect('../trades.db')
cursor = conn.cursor()

try:
    # Get count before deletion
    cursor.execute("SELECT COUNT(*) FROM pricing WHERE price_type = 'close'")
    before_count = cursor.fetchone()[0]
    print(f"Rows with price_type='close' before deletion: {before_count}")
    
    # Delete all close prices
    cursor.execute("DELETE FROM pricing WHERE price_type = 'close'")
    deleted_rows = cursor.rowcount
    print(f"Deleted {deleted_rows} rows")
    
    # Commit the deletion
    conn.commit()
    
    # Verify deletion
    cursor.execute("SELECT COUNT(*) FROM pricing WHERE price_type = 'close'")
    after_count = cursor.fetchone()[0]
    print(f"Rows with price_type='close' after deletion: {after_count}")
    
    # Show total remaining rows
    cursor.execute("SELECT COUNT(*) FROM pricing")
    total_count = cursor.fetchone()[0]
    print(f"\nTotal rows remaining in pricing table: {total_count}")
    
except Exception as e:
    print(f"Error: {e}")
    conn.rollback()
finally:
    conn.close()
    print("\n✓ Database operation complete")

=== REMOVING EXISTING CLOSE PRICES FROM DATABASE ===

Rows with price_type='close' before deletion: 1340
Deleted 1340 rows
Rows with price_type='close' after deletion: 0

Total rows remaining in pricing table: 59

✓ Database operation complete

In [ ]:
# === NORMALIZE SYMBOL SPACING IN COMBINED_DF ===
print("=== NORMALIZING SYMBOL SPACING ===\n")

# Create a copy to work with
normalized_df = combined_df.copy()

# Show current state
print("Before normalization:")
print(f"Total rows: {len(normalized_df)}")

# Check for multiple spaces before normalization
multi_space_before = normalized_df[normalized_df['symbol'].str.contains('  ', regex=False, na=False)]
print(f"Rows with multiple spaces: {len(multi_space_before)}")

# Show some examples with quotes to see spaces
if len(multi_space_before) > 0:
    print("\nExamples of symbols with multiple spaces:")
    for sym in multi_space_before['symbol'].head(5):
        print(f"  '{sym}'")

# Normalize: strip leading/trailing spaces and replace multiple spaces with single space
print("\n\nApplying normalization...")
normalized_df['symbol'] = normalized_df['symbol'].astype(str).str.strip()
normalized_df['symbol'] = normalized_df['symbol'].str.replace(r'\s+', ' ', regex=True)

# Verify normalization
multi_space_after = normalized_df[normalized_df['symbol'].str.contains('  ', regex=False, na=False)]
print(f"\n✓ Normalization complete!")
print(f"Rows with multiple spaces after normalization: {len(multi_space_after)}")

# Also remove any remaining invalid symbols
print("\nRemoving invalid symbols (0, 0.0, empty, numeric-only)...")
before_removal = len(normalized_df)

invalid_mask = (
    (normalized_df['symbol'] == '0') | 
    (normalized_df['symbol'] == '0.0') |
    (normalized_df['symbol'] == '') |
    (normalized_df['symbol'].isna()) |
    (normalized_df['symbol'].str.match(r'^[\d\.]+$', na=False))
)

normalized_df = normalized_df[~invalid_mask]
after_removal = len(normalized_df)

print(f"Removed {before_removal - after_removal} invalid symbols")

# Format timestamp and convert price to string for database insertion
print("\nFormatting for database insertion...")
normalized_df['timestamp'] = normalized_df['timestamp'] + ':00'
normalized_df['price'] = normalized_df['price'].astype(str)

# Final summary
print("\n=== READY FOR DATABASE INSERTION ===")
print(f"Total rows: {len(normalized_df)}")
print(f"Columns: {list(normalized_df.columns)}")
print(f"\nSample data (first 5 rows):")
print(normalized_df[['symbol', 'price_type', 'price', 'timestamp']].head())

# Save to a variable for easy insertion
insert_ready_df = normalized_df.copy()
print("\n✓ Data saved to 'insert_ready_df' variable for insertion")

=== NORMALIZING SYMBOL SPACING ===

Before normalization:
Total rows: 4106
Rows with multiple spaces: 920

Examples of symbols with multiple spaces:
  'TYWN25P5 113.75  Comdty'
  'TYWN25P5 113.5  Comdty'
  'TYWN25P5 113.25  Comdty'
  'TYWN25P5 113  Comdty'
  'TYWN25P5 112.75  Comdty'


Applying normalization...

✓ Normalization complete!
Rows with multiple spaces after normalization: 0

Removing invalid symbols (0, 0.0, empty, numeric-only)...
Removed 575 invalid symbols

Formatting for database insertion...

=== READY FOR DATABASE INSERTION ===
Total rows: 3531
Columns: ['symbol', 'price_type', 'price', 'timestamp']

Sample data (first 5 rows):
                     symbol price_type     price            timestamp
6   VBYN25C2 110.750 Comdty      close  0.015625  2025-07-17 15:00:00
14  VBYN25C2 109.250 Comdty      close  1.515625  2025-07-17 15:00:00
15  VBYN25C2 109.500 Comdty      close  1.265625  2025-07-17 15:00:00
16  VBYN25C2 109.750 Comdty      close  1.015625  2025-07-17 15:00:00
17  VBYN25C2 110.000 Comdty      close  0.765625  2025-07-17 15:00:00

✓ Data saved to 'insert_ready_df' variable for insertion

In [ ]:
# === INSERT NORMALIZED DATA INTO CLEANED DATABASE ===
print("=== INSERTING NORMALIZED DATA INTO DATABASE ===\n")

# Connect to database
conn = sqlite3.connect('../trades.db')
cursor = conn.cursor()

try:
    # Check current state
    cursor.execute("SELECT COUNT(*) FROM pricing")
    initial_count = cursor.fetchone()[0]
    print(f"Current rows in pricing table: {initial_count}")
    
    # Verify no close prices exist
    cursor.execute("SELECT COUNT(*) FROM pricing WHERE price_type = 'close'")
    close_count = cursor.fetchone()[0]
    print(f"Close price rows (should be 0): {close_count}")
    
    if close_count > 0:
        print("\n⚠️ WARNING: Found existing close prices. Clean the database first!")
    else:
        print("\n✓ Database is clean, proceeding with insertion...")
        
        # Convert dataframe to list of tuples for insertion
        records = insert_ready_df[['symbol', 'price_type', 'price', 'timestamp']].values.tolist()
        print(f"\nInserting {len(records)} records...")
        
        # Insert in batches for better performance
        batch_size = 500
        total_inserted = 0
        
        for i in range(0, len(records), batch_size):
            batch = records[i:i+batch_size]
            
            # Use INSERT OR REPLACE to handle any potential conflicts
            cursor.executemany("""
                INSERT OR REPLACE INTO pricing (symbol, price_type, price, timestamp)
                VALUES (?, ?, ?, ?)
            """, batch)
            
            total_inserted += len(batch)
            if i % 2000 == 0:  # Progress update every 4 batches
                print(f"   Progress: {total_inserted}/{len(records)} rows inserted...")
        
        # Commit the transaction
        conn.commit()
        print(f"\n✓ Successfully inserted {total_inserted} records")
        
        # Get final count
        cursor.execute("SELECT COUNT(*) FROM pricing")
        final_count = cursor.fetchone()[0]
        print(f"\nFinal row count in pricing table: {final_count}")
        print(f"Net new rows added: {final_count - initial_count}")
        
        # Show sample of inserted data
        print("\nSample of newly inserted data:")
        cursor.execute("""
            SELECT symbol, price_type, price, timestamp 
            FROM pricing 
            WHERE price_type = 'close' 
            ORDER BY timestamp DESC 
            LIMIT 10
        """)
        
        for row in cursor.fetchall():
            print(f"   {row[0]:<30} | {row[1]:<10} | {row[2]:<10} | {row[3]}")
        
        # Check for any symbols with spaces
        cursor.execute("""
            SELECT COUNT(*) 
            FROM pricing 
            WHERE symbol LIKE '%  %' AND price_type = 'close'
        """)
        multi_space_count = cursor.fetchone()[0]
        print(f"\n✓ Symbols with multiple spaces in database: {multi_space_count}")
        
except Exception as e:
    print(f"❌ Error during insertion: {e}")
    conn.rollback()
    
finally:
    conn.close()
    print("\n✓ Database connection closed")

=== INSERTING NORMALIZED DATA INTO DATABASE ===

Current rows in pricing table: 59
Close price rows (should be 0): 0

✓ Database is clean, proceeding with insertion...

Inserting 3531 records...
   Progress: 500/3531 rows inserted...
   Progress: 2500/3531 rows inserted...

✓ Successfully inserted 3531 records

Final row count in pricing table: 1072
Net new rows added: 1013

Sample of newly inserted data:
   1MQ5P 115 Comdty               | close      | 2.796875   | 2025-08-01 14:01:00
   1MQ5P 114.75 Comdty            | close      | 2.546875   | 2025-08-01 14:01:00
   1MQ5P 114.5 Comdty             | close      | 2.296875   | 2025-08-01 14:01:00
   1MQ5P 114.25 Comdty            | close      | 2.046875   | 2025-08-01 14:01:00
   1MQ5P 114 Comdty               | close      | 1.796875   | 2025-08-01 14:01:00
   1MQ5P 113.75 Comdty            | close      | 1.546875   | 2025-08-01 14:01:00
   1MQ5P 113.5 Comdty             | close      | 1.296875   | 2025-08-01 14:01:00
   1MQ5P 113.25 Comdty            | close      | 1.046875   | 2025-08-01 14:01:00
   1MQ5P 113 Comdty               | close      | 0.796875   | 2025-08-01 14:01:00
   1MQ5P 112.75 Comdty            | close      | 0.546875   | 2025-08-01 14:01:00

✓ Symbols with multiple spaces in database: 0

✓ Database connection closed